### PR TITLE
strip file paths from zip_list; closes #17

### LINKED ISSUE #17: zip::zip_list can return absolute file paths
The `zip::zip_list()` does not necessarily return file names without paths - see [`?zip::zip` for details](https://github.com/r-lib/zip/blob/master/R/zip.R#L26-L56). The following code demonstrates (in a possibly OS-dependent manner, so don't worry if you can't reproduce):

``` r
f <- file.path (tempdir (), "mtcars.csv")
write.table (mtcars, f, sep = ",")
z <- file.path (tempdir (), "my.zip")
utils::zip (z, files = f, flags = "-q")
zip::zip_list (z)
#>                    filename compressed_size uncompressed_size
#> 1 tmp/Rtmp8OkYhX/mtcars.csv             861              1780
#>             timestamp permissions    crc32 offset
#> 1 2021-06-21 08:40:22         666 16e2dfc6      0
```

<sup>Created on 2021-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

In such cases, the names of the items read in `import_gtfs` will be the full paths, and the returned object retains those names. Everything works, but any other packages expecting a gtfs feed to have standard names will then fail. This is what happens:

``` r
library (gtfsrouter)
library (gtfsio)
f <- berlin_gtfs_to_zip ()
g <- gtfsio::import_gtfs (f)
names (g)
#> [1] "tmp/Rtmp2EVj5z/calendar"   "tmp/Rtmp2EVj5z/routes"    
#> [3] "tmp/Rtmp2EVj5z/trips"      "tmp/Rtmp2EVj5z/stop_times"
#> [5] "tmp/Rtmp2EVj5z/stops"      "tmp/Rtmp2EVj5z/transfers"
```

<sup>Created on 2021-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

I'll submit a PR to fix the names once #16 has been merged. The package will then need a final `check_gtfs_format()` or `gtfsio_is_valid()` or similar function that confirms that everything has the expected format - that all required tables are present, and that all required columns of required tables are also present. We can worry about that once #16 and this issue have been addressed. :+1:

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

File: R/import_gtfs.R [hunk 1]
```diff
@@ -187,9 +187,14 @@ import_gtfs <- function(path,
     quiet
   )
 
-  # assign names to 'gtfs'
-
-  names(gtfs) <- files_to_read
+  # assign names to 'gtfs', noting that zip_list may return full paths, which
+  # need to be stripped here
+
+  file_names <- vapply (files_in_gtfs, function (i)
```
Comment (dhersz) [inline R/import_gtfs.R:193]: The `vapply()` should be applied to `files_to_read`, and not `files_in_gtfs` (a file may be inside the GTFS but the user may want to skip it using the `files` or `skip` parameters). This is probably why the PR didn't pass the checks.

**Review by dhersz — CHANGES_REQUESTED** [review]
Thanks for the PR @mpadge. I found one small error in it, it should be good to merge after fixing it!

**Comment by dhersz** [comment]
Cool, thanks for the quick fix!
